export const FORM_FIELDS = [
  {
    id: 0,
    label: "Borç Adı*",
    name: "debtName",
    type: "text",
    placeholder: "Borç Adı",
    required: true,
  },
  {
    id: 1,
    label: "Borç Veren*",
    name: "lenderName",
    type: "text",
    placeholder: "Borç Veren",
    required: true,
  },
  {
    id: 2,
    label: "Borç Tutarı*",
    name: "debAmount",
    type: "number",
    placeholder: "Borç Tutarı",
    required: true,
  },
  {
    id: 3,
    label: "Faiz Oranı*",
    name: "interestRate",
    type: "number",
    placeholder: "Faiz Oranı",
    required: true,
  },
  {
    id: 6,
    label: "Taksit Sayısı*",
    name: "installment",
    type: "number",
    placeholder: "Taksit Sayısı",
    required: true,
  },
  {
    id: 5,
    label: "Başlangıç Tarihi*",
    name: "paymentStart",
    type: "date",
    placeholder: "Başlangıç Tarihi",
    required: true,
  },
  {
    id: 7,
    label: "Açıklama",
    name: "description",
    type: "text",
    placeholder: "Açıklama",
    required: false,
  },
];
